=== christof337/pf2_data/trait.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1"
           elementFormDefault="qualified">

  <xs:element name="traits">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="trait" type="traitType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="traitType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:richTextType"/>
      <xs:attribute name="source" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="richTextType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="table" type="tableType"/>
      <xs:element name="list" type="listType"/>
      <xs:element name="spell" type="xs:string"/>
      <xs:element name="scseecBloc" type="scseecType"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tableType">
    <xs:sequence>
      <xs:element name="headerLine" type="rowType" minOccurs="0"/>
      <xs:element name="line" type="rowType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element name="cell" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="listType">
    <xs:sequence>
      <xs:element name="listItem" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="special" type="specialAbilityType" minOccurs="0"/>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/> 
          </xs:sequence>
          <xs:anyAttribute processContents="skip"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="scseecType">
    <xs:sequence>
      <xs:element name="criticalSuccess" type="xs:string" minOccurs="0"/>
      <xs:element name="success" type="xs:string" minOccurs="0"/>
      <xs:element name="failure" type="xs:string" minOccurs="0"/>
      <xs:element name="criticalFailure" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== christof337/pf2_data/tests/fixtures/test_traits_ok.xml
<?xml version='1.0' encoding='UTF-8'?>
<traits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schema/trait.xsd">
  <trait id="trait-commune">
    <name>Commune</name>
    <description>Une créature qui possède cette rareté est courante et peut être convoquée à l’aide du sort de convocation approprié.</description>
  </trait>
  <trait id="trait-peu-courante">
    <name>Peu courante</name>
    <description>On en sait moins sur les créatures peu courantes que sur les créatures communes. Elles ne peuvent généralement pas être convoquées. Le DD des tests permettant de Se souvenir d’informations sur une telle créature est augmenté de 2.</description>
  </trait>
  <trait id="trait-rare">
    <name>Rare</name>
    <description>Comme le nom l’indique, ces créatures sont rares. Elles ne peuvent généralement pas être convoquées. Le DD des tests permettant de Se souvenir d’informations sur une telle créature est augmenté de 5.</description>
  </trait>
  <trait id="trait-unique">
    <name>Unique</name>
    <description>Une créature qui possède cette rareté est la seule de son espèce. Le DD des tests permettant de Se souvenir d’informations sur une telle créature est augmenté de 10.</description>
  </trait>
  <trait id="trait-gigantesque">
    <name>Gigantesque</name>
    <description>Une créature de taille Gigantesque occupe un espace d’au moins 6 m sur 6 m (soit 16 cases sur le quadrillage), mais certaines sont bien plus grandes. Les créatures Gigantesques ont généralement une allonge de 6 m si elles sont hautes ou de 4,5 m si elles sont longues, mais les plus grandes peuvent avoir une allonge bien supérieure.</description>
  </trait>
  <trait id="trait-tres-grande">
    <name>Très Grande</name>
    <description>Une créature de Très Grande taille occupe un espace de 4,5 m sur 4,5 m (9 cases sur le quadrillage). Elle a généralement une allonge de 4,5 m si elle est haute ou de 3 m si elle est longue.</description>
  </trait>
  <trait id="trait-grande">
    <name>Grande</name>
    <description>Une créature de Grande taille occupe un espace de 3 m sur 3 m (4 cases sur le quadrillage). Elle a généralement une allonge de 3 m si elle est haute ou de 1,5 m si elle est longue.</description>
  </trait>
  <trait id="trait-moyenne">
    <name>Moyenne</name>
    <description>Une créature de taille Moyenne occupe un espace de 1,5 m sur 1,5 m (1 case sur le quadrillage) et a généralement une allonge de 1,5 m.</description>
  </trait>
  <trait id="trait-petite">
    <name>Petite</name>
    <description>Une créature de Petite taille occupe un espace de 1,5 m sur 1,5 m (1 case sur le quadrillage) et a généralement une allonge de 1,5 m.</description>
  </trait>
  <trait id="trait-tres-petite">
    <name>Très Petite</name>
    <description>Une créature de Très Petite taille occupe un espace inférieur à 1,5 m sur 1,5 m (1 case sur le quadrillage), et plusieurs Très Petites créatures peuvent occuper la même case sur le quadrillage. Une même case peut être occupée par au moins quatre créatures de Très Petites taille, et même plus si le MJ le permet. Elles peuvent également occuper le même espace que des créatures de taille supérieure et, si leur allonge est de 0 m, elles y sont même forcées pour pouvoir attaquer.</description>
  </trait>
  <trait id="trait-aberration">
    <name>aberration</name>
    <description>Les aberrations sont des créatures venant d’au-delà des plans ou des créatures naturelles corrompues.</description>
  </trait>
  <trait id="trait-air">
    <name>air</name>
    <description>Les effets dotés du trait air permettent de manipuler ou de créer de l’air. Ceux qui permettent de manipuler l’air n’ont aucun effet dans le vide ou une zone dépourvue d’air. Les créatures dotées de ce trait sont essentiellement constituées d’air ou ont une connexion magique avec cet élément.</description>
  </trait>
  <trait id="trait-aiuvarin">
    <name>aiuvarin</name>
    <description>Les aiuvarins ont des origines mixtes et ont généralement un parent elfe et un aiuvarin ou humain.</description>
  </trait>
  <trait id="trait-alchimique">
    <name>alchimique</name>
    <description>Les objets alchimiques fonctionnent grâce à des réactifs alchimiques. Ils ne sont pas magiques et n’émettent pas d’aura magique. Les créatures alchimiques sont partiellement animées par des réactions alchimiques.</description>
  </trait>
  <trait id="trait-ames">
    <name>âmes</name>
    <description>Ces créatures artificielles reçoivent une augmentation mentale sous la forme d’un fragment d’âme d’une créature qui a été vivante.</description>
  </trait>
  <trait id="trait-ame-en-peine">
    <name>âme-en-peine</name>
    <description>Une âme-en-peine est une créature morte-vivante intangible imprégnée d’énergie du néant et animée d’une profonde haine pour la vie.</description>
  </trait>
  <trait id="trait-amphibie">
    <name>amphibie</name>
    <description>Une créature amphibie peut respirer dans l’eau et dans l’air, même si elle se trouve hors de son environnement de prédilection, généralement sans limites de temps ou au moins pendant plusieurs heures. Ces créatures disposent souvent d’une Vitesse de nage. Leurs Frappes contondantes et tranchantes à mains nues ne subissent pas le malus habituel de −2 lié à l’environnement aquatique.</description>
  </trait>
  <trait id="trait-ange">
    <name>ange</name>
    <description>Les membres de cette famille de célestes sont des messagers et des guerriers. La majorité des anges possèdent le trait saint, vision dans le noir et souffrent d’une faiblesse contre ce qui est impie.</description>
  </trait>
  <trait id="trait-animal">
    <name>animal</name>
    <description>Un animal est une créature dont l’intelligence est relativement limitée. Son modificateur d’attribut d’Intelligence ne dépasse généralement pas −4, il ne peut pas parler de langue ni développer de compétences basées sur l’Intelligence.</description>
  </trait>
  <trait id="trait-aquatique">
    <name>aquatique</name>
    <description>Les créatures aquatiques vivent sous l’eau. Leurs Frappes contondantes et tranchantes à mains nues ne subissent pas le malus habituel de −2 lié à l’environnement aquatique. Les créatures aquatiques peuvent respirer dans l’eau, mais pas à l’air libre.</description>
  </trait>
  <trait id="trait-arcane">
    <name>arcane</name>
    <description>Cette magie découle de la tradition arcanique, qui repose sur la logique et la rationalité. Tout ce qui est doté de ce trait est magique. Une créature pourvue de ce trait est essentiellement constituée de magie arcanique ou a une forte connexion avec elle.</description>
  </trait>
  <trait id="trait-archon">
    <name>archon</name>
    <description>Les membres de cette famille de célestes sont les protecteurs du Paradis et possèdent généralement le trait saint, vision dans le noir et souffrent d’une faiblesse contre ce qui est impie.</description>
  </trait>
  <trait id="trait-astral">
    <name>astral</name>
    <description>Les créatures astrales sont originaires du plan astral, et peuvent survivre à ses effets environnementaux basiques.</description>
  </trait>
  <trait id="trait-athamaru">
    <name>athamaru</name>
    <description>Les athamarus sont des humanoïdes aquatiques aux traits de poisson.</description>
  </trait>
  <trait id="trait-azarketi">
    <name>azarketi</name>
    <description>Les azarketis descendent des humains et se sont adaptés à la vie dans des communautés aquatiques. Ils ont des ouïes, des mains palmées, des petites nageoires et peuvent survivre dans l’eau comme en dehors.</description>
  </trait>
  <trait id="trait-azata">
    <name>azata</name>
    <description>Cette famille de célestes est originaire de l’Élysée. Ils possèdent généralement le trait saint, vision dans le noir, et souffrent d’une faiblesse au fer froid et à ce qui est impie. FRANCK PONT - lhanselo@hotmail.fr - 202602/3379711/4016001 [[PAGE 2]] # FLUX PRINCIPAL (STATS/BASE) Livre des Monstres</description>
  </trait>
  <trait id="trait-bourbierin">
    <name>bourbiérin</name>
    <description>Les bourbiérins sont des humanoïdes à l’aspect de batraciens. Ils possèdent généralement le sens vision dans le noir.</description>
  </trait>
  <trait id="trait-caligni">
    <name>caligni</name>
    <description>Ce peuple souterrain possède vision dans le noir, et certains individus peuvent créer des ténèbres.</description>
  </trait>
  <trait id="trait-celeste">
    <name>céleste</name>
    <description>Les créatures qui sont originaires des plans saints ou qui bénéficient d’une connexion importante avec eux sont appelées des célestes. Les célestes peuvent survivre aux effets environnementaux de base des plans de la Sphère extérieure.</description>
  </trait>
  <trait id="trait-centaure">
    <name>centaure</name>
    <description>Les centaures sont des créatures qui possèdent un corps de cheval et un buste humanoïde.</description>
  </trait>
  <trait id="trait-champignon">
    <name>champignon</name>
    <description>Les créatures fongiques sont dotées du trait champignon. Elles sont à distinguer des champignons normaux.</description>
  </trait>
  <trait id="trait-changelin">
    <name>changelin</name>
    <description>Une créature dotée de ce trait possède l’héritage polyvalent changelin. Les changelins sont les rejetons de guenaudes et de membres d’autres ascendances humanoïdes.</description>
  </trait>
  <trait id="trait-coatl">
    <name>coatl</name>
    <description>Un type de serpents à plumes surnaturels qui font office de gardiens ou de messagers pour des divinités saintes de l’Univers.</description>
  </trait>
  <trait id="trait-creature-artificielle">
    <name>créature artificielle</name>
