=== christof337/pf2_data/xslt/spell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1"
           elementFormDefault="qualified">
  
  <xs:element name="spells">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="spell" type="spellType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="spellType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      
      <xs:element name="type" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="rank">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      
      <xs:element name="actions" type="xs:string" minOccurs="0"/>
      
      <xs:element name="traits" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="trait" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="traditions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tradition" type="traditionType" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="cast" type="xs:string" minOccurs="0"/>
      <xs:element name="range" type="xs:string" minOccurs="0"/>
      <xs:element name="area" type="xs:string" minOccurs="0"/>
      <xs:element name="targets" type="xs:string" minOccurs="0"/>
      <xs:element name="defense" type="xs:string" minOccurs="0"/>
      <xs:element name="duration" type="xs:string" minOccurs="0"/>
      
      <xs:element name="description" type="richTextType"/>
      
      <xs:element name="savingThrow" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="criticalSuccess" type="richTextType" minOccurs="0"/>
            <xs:element name="success" type="richTextType" minOccurs="0"/>
            <xs:element name="failure" type="richTextType" minOccurs="0"/>
            <xs:element name="criticalFailure" type="richTextType" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="heightenList" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="heighten" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                  <xs:element name="spellRef" type="xs:string"/>
                </xs:choice>
                <xs:attribute name="type" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="richTextType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="spellRef" type="xs:string"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:simpleType name="traditionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="arcanique"/>
      <xs:enumeration value="occulte"/>
      <xs:enumeration value="primordiale"/>
      <xs:enumeration value="divine"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== christof337/pf2_data/xslt/spell.xml
<?xml version="1.0" encoding="UTF-8"?>
<spells xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spell.xsd">
    <spell>
        <name>AGITATION</name>
        <rank>1</rank>
        <actions>2</actions>
        
        <traits>
            <trait>CONCENTRATION</trait>
            <trait>MANIPULATION</trait>
            <trait>MENTAL</trait>
            <trait>NON LÉTAL</trait>
        </traits>
        
        <traditions>
            <tradition>arcanique</tradition>
            <tradition>occulte</tradition>
        </traditions>
        
        <range>9 m</range>
        <targets>1 créature</targets>
        <defense>Volonté</defense>
        <duration>variable</duration>
        
        <description>Le corps et l’esprit de votre cible sont stimulés de façon excessive et elle est prise de frénésie hyperactive. Pendant la durée, la cible doit Marcher rapidement, Voler ou Nager au moins une fois par tour ou subir 2d8 dégâts mentaux à la fin de son tour. Le MJ peut décider d’ajouter des actions de déplacement supplémentaires à la liste pour les créatures qui ne possèdent qu’une forme de déplacement inhabituelle. La durée du sort dépend du jet de Volonté de la cible.</description>
        
        <savingThrow>
            <criticalSuccess>Le sort n’a aucun effet.</criticalSuccess>
            <success>La durée est de 1 round.</success>
            <failure>La durée est de 2 rounds.</failure>
            <criticalFailure>La durée est de 4 rounds.</criticalFailure>
        </savingThrow>
        
        <heightenList>
            <heighten type="+1">Les dégâts sont augmentés de 2d8.</heighten>
        </heightenList>
    </spell>
</spells>
